export const menuCategories = ['All', 'Starters', 'Mains', 'Breads', 'Desserts', 'Beverages'];

export const menuItems = [
  {
    name: 'Paneer Tikka Lasooni',
    category: 'Starters',
    price: 420,
    veg: true,
    jain: false,
    tags: ["CHEF'S SPECIAL"],
    description: 'Smoked cottage cheese marinated in garlic, hung curd and mustard oil, finished in the clay tandoor.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Murgh Malai Kebab',
    category: 'Starters',
    price: 520,
    veg: false,
    jain: false,
    tags: ["CHEF'S SPECIAL"],
    description: 'Cream-cheese marinated chicken charred over slow coals, served with mint chutney.',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Dahi Ke Kebab',
    category: 'Starters',
    price: 380,
    veg: true,
    jain: true,
    tags: ['JAIN'],
    description: 'Crisped hung-curd patties with roasted spices — a Lucknowi classic done the Jain way.',
    image: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Tandoori Soya Chaap',
    category: 'Starters',
    price: 360,
    veg: true,
    jain: true,
    tags: ['JAIN'],
    description: 'Smoky soya chaap skewers in a cashew-melon seed marinade, straight from the tandoor.',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Hara Bhara Kebab',
    category: 'Starters',
    price: 340,
    veg: true,
    jain: false,
    tags: [],
    description: 'Spinach, green peas and potato patties with a molten cheese heart, beetroot mayo on the side.',
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Crispy Corn Salt & Pepper',
    category: 'Starters',
    price: 320,
    veg: true,
    jain: true,
    tags: ['SPICY'],
    description: 'Golden-fried baby corn tossed with burnt garlic, cracked pepper and spring onion.',
    image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Dal Saat Vachan',
    category: 'Mains',
    price: 460,
    veg: true,
    jain: false,
    tags: ["TODAY'S SPECIAL"],
    description: 'Our signature seven-lentil dal, simmered overnight and tempered in white butter.',
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Paneer Lababdar',
    category: 'Mains',
    price: 440,
    veg: true,
    jain: false,
    tags: ["CHEF'S SPECIAL"],
    description: 'Hand-torn paneer folded through a rich tomato-onion makhani with kasuri methi.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Butter Chicken',
    category: 'Mains',
    price: 540,
    veg: false,
    jain: false,
    tags: ['MOST LOVED'],
    description: 'Tandoor-roasted chicken simmered in a silken tomato-fenugreek gravy, finished with cream.',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Kadhai Vegetables',
    category: 'Mains',
    price: 380,
    veg: true,
    jain: true,
    tags: ['JAIN'],
    description: 'Crunchy garden vegetables tossed in freshly pounded kadhai masala — no onion, no garlic.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Shahi Kofta',
    category: 'Mains',
    price: 420,
    veg: true,
    jain: false,
    tags: [],
    description: 'Velvet paneer-kofta dumplings in a royal cashew gravy scented with saffron.',
    image: 'https://images.unsplash.com/photo-1585938389612-a552a28d6914?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Subz Dum Biryani',
    category: 'Mains',
    price: 420,
    veg: true,
    jain: false,
    tags: ['DUM STYLE'],
    description: 'Layered basmati with saffron, fried onions and seasonal vegetables, sealed and slow-steamed.',
    image: 'https://images.unsplash.com/photo-1563379926898-05f4575a45d8?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Murgh Dum Biryani',
    category: 'Mains',
    price: 520,
    veg: false,
    jain: false,
    tags: ['DUM STYLE', 'SPICY'],
    description: 'Overnight-marinated chicken layered with aged basmati, served with mirchi ka salan and raita.',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Rajma Masala',
    category: 'Mains',
    price: 360,
    veg: true,
    jain: true,
    tags: ['JAIN'],
    description: 'Slow-cooked red kidney beans in a homestyle tomato gravy — comfort in a handi.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Tandoori Roti Basket',
    category: 'Breads',
    price: 180,
    veg: true,
    jain: true,
    tags: ['TANDOOR FRESH'],
    description: 'A basket of four — tandoori roti, butter roti, missi and plain paratha, brushed with ghee.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Garlic Naan',
    category: 'Breads',
    price: 220,
    veg: true,
    jain: false,
    tags: ['TANDOOR FRESH'],
    description: 'Pillowy tandoor naan showered with roasted garlic, coriander and a butter glaze.',
    image: 'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Laccha Paratha',
    category: 'Breads',
    price: 200,
    veg: true,
    jain: true,
    tags: [],
    description: 'Sixteen flaky layers of whole-wheat paratha, crushed between the palms and served hot.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Gulab Jamun (4 pc)',
    category: 'Desserts',
    price: 180,
    veg: true,
    jain: true,
    tags: ['SERVED HOT'],
    description: 'Khoya dumplings soaked in rose-cardamom syrup, served warm with a silver varq.',
    image: 'https://images.unsplash.com/photo-1666190092159-3171cf0fbb12?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Kulfi Falooda',
    category: 'Desserts',
    price: 240,
    veg: true,
    jain: true,
    tags: [],
    description: 'Dense malai kulfi over rose falooda with basil seeds, dry fruit and a saffron drizzle.',
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Rasmalai',
    category: 'Desserts',
    price: 220,
    veg: true,
    jain: true,
    tags: [],
    description: 'Feather-light chenna discs resting in chilled saffron milk with pistachio dust.',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Sizzling Chocolate Brownie',
    category: 'Desserts',
    price: 280,
    veg: true,
    jain: true,
    tags: ["CHEF'S SPECIAL"],
    description: 'Walnut brownie on a hot sizzler with vanilla scoop, poured-over dark chocolate sauce.',
    image: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Masala Shikanji',
    category: 'Beverages',
    price: 180,
    veg: true,
    jain: true,
    tags: ['SUMMER COOLER'],
    description: 'Old-Delhi style spiced lemonade with roasted cumin, black salt and fresh mint.',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Sweet Punjabi Lassi',
    category: 'Beverages',
    price: 200,
    veg: true,
    jain: true,
    tags: [],
    description: 'Thick curd churned with malai topping and a whisper of cardamom, served in a tall glass.',
    image: 'https://images.unsplash.com/photo-1626200419199-391ae4be7a41?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Masala Chaas',
    category: 'Beverages',
    price: 180,
    veg: true,
    jain: true,
    tags: [],
    description: 'Salted buttermilk whisked with curry leaf, green chilli and roasted jeera.',
    image: 'https://images.unsplash.com/photo-1437418747212-8d9709afab22?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Cold Coffee',
    category: 'Beverages',
    price: 220,
    veg: true,
    jain: true,
    tags: [],
    description: 'Slow-blended espresso, chilled milk and vanilla ice cream crowned with cocoa.',
    image: 'https://images.unsplash.com/photo-1517959105821-eaf2591984ca?q=80&w=800&auto=format&fit=crop',
  },
  {
    name: 'Kulhad Masala Chai',
    category: 'Beverages',
    price: 180,
    veg: true,
    jain: true,
    tags: [],
    description: 'Assam leaves brewed with crushed ginger and garam masala, served bubbling in earthen kulhads.',
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?q=80&w=800&auto=format&fit=crop',
  },
];
